### ISSUE TITLE
Add documentation to values.yaml on how to include secrets

### ISSUE THREAD

**Issue by KristapsT** [vmware-tanzu/helm-charts#28]
I am installing Velero in K8s cluster that will use Azure Storabe blob as backed, using latest chart version 2.7.5, but I am getting the following error in Velero logs on startup:

```
time="2020-01-02T11:33:46Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:171"
time="2020-01-02T11:33:46Z" level=info msg="Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/server/server.go:173"
time="2020-01-02T11:33:46Z" level=info msg="No feature flags enabled" logSource="pkg/cmd/server/server.go:177"
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-01-02T11:33:46Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:337" namespace=velero
time="2020-01-02T11:33:46Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:343" namespace=velero
time="2020-01-02T11:33:49Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:372"
time="2020-01-02T11:33:49Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:406"
time="2020-01-02T11:33:49Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory
```

Here is my valuesfile:

```
##
## Configuration settings that directly affect the Velero deployment YAML.
##

# Details of the container image to use in the Velero deployment & daemonset (if
# enabling restic). Required.
image:
  repository: velero/velero
  tag: v1.2.0
  pullPolicy: IfNotPresent

# Annotations to add to the Velero deployment's pod template. Optional.
#
# If using kube2iam or kiam, use the following annotation with your AWS_ACCOUNT_ID
# and VELERO_ROLE_NAME filled in:
#  iam.amazonaws.com/role: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<VELERO_ROLE_NAME>
podAnnotations: {}

# Resource requests/limits to specify for the Velero deployment. Optional.
resources: {}

# Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
initContainers:
   - name: velero-plugin-for-microsoft-azure
     image: velero/velero-plugin-for-microsoft-azure:v1.0.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - name: plugins
         mountPath: /target

# Tolerations to use for the Velero deployment. Optional.
tolerations: []

# Node selector to use for the Velero deployment. Optional.
nodeSelector: {}

# Extra volumes for the Velero deployment. Optional.
extraVolumes:

# Extra volumeMounts for the Velero deployment. Optional.
extraVolumeMounts: []

# Settings for Velero's prometheus metrics. Enabled by default.
metrics:
  enabled: true
  scrapeInterval: 15s

  # Pod annotations for Prometheus
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    enabled: false
    additionalLabels: {}

##
## End of deployment-related settings.
##



##
## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
## and additional server settings.
##
configuration:
  provider: azure

  # Parameters for the `default` BackupStorageLocation. See
  # https://velero.io/docs/v1.0.0/api-types/backupstoragelocation/
  backupStorageLocation:
    name: azure
    bucket: <redacted>
    prefix: test
    config:
      resourceGroup: <redacted>
      storageAccount: <redacted>

  # These are server-level settings passed as CLI flags to the `velero server` command. Velero
  # uses default values if they're not passed in, so they only need to be explicitly specified
  # here if using a non-default value. The `velero server` default values are shown in the
  # comments below.
  # --------------------
  # `velero server` default: 1m
  backupSyncPeriod: 60m
  # `velero server` default: 1h
  resticTimeout:
  # `velero server` default: namespaces,persistentvolumes,persistentvolumeclaims,secrets,configmaps,serviceaccounts,limitranges,pods
  restoreResourcePriorities:
  # `velero server` default: false
  restoreOnlyMode:

  # additional key/value pairs to be used as environment variables such as "AWS_CLUSTER_NAME: 'yourcluster.domain.tld'"
  extraEnvVars: {}

  # Set log-level for Velero pod. Default: info. Other options: debug, warning, error, fatal, panic.
  logLevel:

  # Set log-format for Velero pod. Default: text. Other option: json.
  logFormat:

##
## End of backup/snapshot location settings.
##



##
## Settings for additional Velero resources.
##

# Whether to create the Velero cluster role binding.
rbac:
  create: true

# Information about the Kubernetes service account Velero uses.
serviceAccount:
  server:
    create: true
    name:

# Info about the secret to be used by the Velero deployment, which
# should contain credentials for the cloud provider IAM account you've
# set up for Velero.
credentials:
  existingSecret: "cloud-credentials"
  useSecret: true

# Wheter to create volumesnapshotlocation crd, if false => disable snapshot feature
snapshotsEnabled: false

# Whether to deploy the restic daemonset.
deployRestic: false

schedules: 
  daily-backup:
    schedule: "0 17 * * *"
    template:
      ttl: "120h"
      excludedNamespaces:
        - global-infrastructure

configMaps: {}

##
## End of additional Velero resource settings.
##
```

And here are the contents of pre-existing secret "cloud-credentials" in the namespace where velero is being installed:
```
apiVersion: v1
data:
  AZURE_CLIENT_ID: <redacted>
  AZURE_CLIENT_SECRET: <redacted>
  AZURE_CLOUD_NAME: <redacted>
  AZURE_RESOURCE_GROUP: <redacted>
  AZURE_SUBSCRIPTION_ID: <redacted>
  AZURE_TENANT_ID: <redacted>
kind: Secret
metadata:
  creationTimestamp: "2020-01-02T11:07:22Z"
  labels:
    CREATED_BY: terraform
  name: cloud-credentials
  namespace: velero
  resourceVersion: "43307401"
  selfLink: /api/v1/namespaces/velero/secrets/cloud-credentials
  uid: 0d031617-2d50-11ea-a618-e29387fbefef
type: Opaque
```

Am I doing anything wrong with my configuration?

**Comment by KristapsT** [comment]
I figured this out, I was providing bad existing K8s secret to the chart, the data of secret should be one value "cloud" that in turn contains all required credentials like so:
```
apiVersion: v1
data:
  cloud: <base64 encoded string>
kind: Secret
metadata:
  creationTimestamp: "2020-01-02T11:07:22Z"
  labels:
    CREATED_BY: terraform
  name: cloud-credentials
  namespace: velero
  resourceVersion: "43493203"
  selfLink: /api/v1/namespaces/velero/secrets/cloud-credentials
  uid: 0d031617-2d50-11ea-a618-e29387fbefef
type: Opaque
```

where cloud value when decoded is:
```
AZURE_CLIENT_ID=<redacted>
AZURE_CLIENT_SECRET=<redacted>
AZURE_CLOUD_NAME=<redacted>
AZURE_RESOURCE_GROUP=<redacted>
AZURE_SUBSCRIPTION_ID=<redacted>
AZURE_TENANT_ID=<redacted>
```

Worked fine after fixing the secret.

Maybe a better documentation about what's required of the pre-existing is needed?

**Comment by previ** [comment]
A secret does get created but the name and format is different than expected.
So it's probably a bug in the chart.

**Comment by vterdunov** [comment]
Looks like this lines should be fixed
- https://github.com/vmware-tanzu/helm-charts/blob/7a1ffd05eacc12fc6bee597f15a877cfd4c894db/charts/velero/templates/deployment.yaml#L129
- https://github.com/vmware-tanzu/helm-charts/blob/7a1ffd05eacc12fc6bee597f15a877cfd4c894db/charts/velero/templates/deployment.yaml#L77

From `"velero.secretName"` to `.Values.credentials.existingSecret`

**Comment by MiyKh** [comment]
Is it fixed in latest velero chart (2.9.3)?
I still have the error:
``` 
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory
```

**Comment by nrb** [comment]
@MiyKh The latest version of the chart should be 2.11.0, which came out with the v1.4.0 release.

**Comment by v-y-a-s** [comment]
I still see this - Chart - 

`dependencies:
- name: velero
  version: "2.12.13"
  repository: "https://vmware-tanzu.github.io/helm-charts/"`


`time="2020-08-12T14:43:33Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:177"
time="2020-08-12T14:43:33Z" level=info msg="Starting Velero server v1.4.0 (5963650c9d64643daaf510ef93ac4a36b6483392)" logSource="pkg/cmd/server/server.go:179"
time="2020-08-12T14:43:33Z" level=info msg="No feature flags enabled" logSource="pkg/cmd/server/server.go:183"
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-08-12T14:43:34Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-08-12T14:43:34Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2020-08-12T14:43:34Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:367" namespace=velero
time="2020-08-12T14:43:36Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:396"
time="2020-08-12T14:43:41Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:430"
time="2020-08-12T14:43:41Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: error getting backup store for location "azure": rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory; error getting backup store for location "default": rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory`

**Comment by nrb** [comment]
@v-y-a-s I'm assuming the first example is Helm 2, since you explicitly mention Helm 3 in the 2nd?

**Comment by v-y-a-s** [comment]
> @v-y-a-s I'm assuming the first example is Helm 2, since you explicitly mention Helm 3 in the 2nd?

Sorry for inconsistent report. both are HELM 3. 

The first one was done using dependency in a new helm3 chart and configuring the secrets. 

The second one was done using helm3 command line. 

The chart's values.yaml

```
velero:
  ##
  ## Configuration settings that directly affect the Velero deployment YAML.
  ##

  # Details of the container image to use in the Velero deployment & daemonset (if
  # enabling restic). Required.
  image:
    repository: velero/velero
    tag: v1.4.0
    # Digest value example: sha256:d238835e151cec91c6a811fe3a89a66d3231d9f64d09e5f3c49552672d271f38. If used, it will
    # take precedence over the image.tag.
    # digest:
    imagePullPolicy: IfNotPresent

  # Annotations to add to the Velero deployment's pod template. Optional.
  #
  # If using kube2iam or kiam, use the following annotation with your AWS_ACCOUNT_ID
  # and VELERO_ROLE_NAME filled in:
  #  iam.amazonaws.com/role: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<VELERO_ROLE_NAME>
  podAnnotations: {}

  # Additional pod labels for Velero deployment's template. Optional
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

  # Resource requests/limits to specify for the Velero deployment. Optional.
  resources: {}

  # Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
  initContainers:
    - name: velero-plugin-for-microsoft-azure
      image: velero/velero-plugin-for-microsoft-azure:main
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /target
          name: plugins

  # SecurityContext to use for the Velero deployment. Optional.
  # Set fsGroup for `AWS IAM Roles for Service Accounts`
  # see more informations at: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
  securityContext: {}
    # fsGroup: 1337

  # Tolerations to use for the Velero deployment. Optional.
  tolerations: []

  # Affinity to use for the Velero deployment. Optional.
  affinity: {}

  # Node selector to use for the Velero deployment. Optional.
  nodeSelector: {}

  # Extra volumes for the Velero deployment. Optional.
  extraVolumes: []

  # Extra volumeMounts for the Velero deployment. Optional.
  extraVolumeMounts: []

  # Settings for Velero's prometheus metrics. Enabled by default.
  metrics:
    enabled: true

    # Pod annotations for Prometheus
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8085"
      prometheus.io/path: "/metrics"

  # Install CRDs as a templates. Enabled by default.
  installCRDs: true

  ##
  ## End of deployment-related settings.
  ##


  ##
  ## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
  ## and additional server settings.
  ##
  configuration:
    # Cloud provider being used (e.g. aws, azure, gcp).
    provider: azure

    # Parameters for the `default` BackupStorageLocation. See
    # https://velero.io/docs/v1.4/api-types/backupstoragelocation/
    backupStorageLocation:
      # name is the name of the backup storage location where backups should be stored. If a name is not provided,
      # a backup storage location will be created with the name "default". Optional.
      name: "azure"
      # provider is the name for the backup storage location provider. If omitted
      # `configuration.provider` will be used instead.
      provider: "azure"
      # bucket is the name of the bucket to store backups in. Required.
      bucket: "database"
      # caCert defines a CA bundle to use when verifying TLS connections to the provider.
      caCert:
        # type is byte
        format:
        # type is string
        type:
      # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
      prefix:
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config: 
        resourceGroup: "common"
        storageAccount: "notionedgebackups"
      #  region:
      #  s3ForcePathStyle:
      #  s3Url:
      #  kmsKeyId:
      #  resourceGroup:
      #  The ID of the subscription containing the storage account, if different from the cluster’s subscription. (Azure only)
      #  subscriptionId:
      #  storageAccount:
      #  publicUrl:
      #  Name of the GCP service account to use for this backup storage location. Specify the
      #  service account here if you want to use workload identity instead of providing the key file.(GCP only)
      #  serviceAccount:

    # Parameters for the `default` VolumeSnapshotLocation. See
    # https://velero.io/docs/v1.4/api-types/volumesnapshotlocation/
    volumeSnapshotLocation:
      # name is the name of the volume snapshot location where snapshots are being taken. Required.
      name:
      # provider is the name for the volume snapshot provider. If omitted
      # `configuration.provider` will be used instead.
      provider:
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config: {}
    #    region:
    #    apitimeout:
    #    resourceGroup:
    #    The ID of the subscription where volume snapshots should be stored, if different from the cluster’s subscription. If specified, also requires `configuration.volumeSnapshotLocation.config.resourceGroup`to be set. (Azure only)
    #    subscriptionId:
    #    snapshotLocation:
    #    project:

    # These are server-level settings passed as CLI flags to the `velero server` command. Velero
    # uses default values if they're not passed in, so they only need to be explicitly specified
    # here if using a non-default value. The `velero server` default values are shown in the
    # comments below.
    # --------------------
    # `velero server` default: 1m
    backupSyncPeriod:
    # `velero server` default: 1h
    resticTimeout:
    # `velero server` default: namespaces,persistentvolumes,persistentvolumeclaims,secrets,configmaps,serviceaccounts,limitranges,pods
    restoreResourcePriorities:
    # `velero server` default: false
    restoreOnlyMode:

    # additional key/value pairs to be used as environment variables such as "AWS_CLUSTER_NAME: 'yourcluster.domain.tld'"
    extraEnvVars: {}

    # Comma separated list of velero feature flags. default: empty
    features:

    # Set log-level for Velero pod. Default: info. Other options: debug, warning, error, fatal, panic.
    logLevel:

    # Set log-format for Velero pod. Default: text. Other option: json.
    logFormat:

  ##
  ## End of backup/snapshot location settings.
  ##


  ##
  ## Settings for additional Velero resources.
  ##

  rbac:
    # Whether to create the Velero role and role binding to give all permissions to the namespace to Velero.
    create: true
    # Whether to create the cluster role binding to give administrator permissions to Velero
    clusterAdministrator: true

  # Information about the Kubernetes service account Velero uses.
  serviceAccount:
    server:
      create: true
      name:
      annotations:

  # Info about the secret to be used by the Velero deployment, which
  # should contain credentials for the cloud provider IAM account you've
  # set up for Velero.
  credentials:
    # Whether a secret should be used as the source of IAM account
    # credentials. Set to false if, for example, using kube2iam or
    # kiam to provide IAM credentials for the Velero pod.
    useSecret: true
    # Name of a pre-existing secret (if any) in the Velero namespace
    # that should be used to get IAM account credentials. Optional.
    existingSecret:
    # Data to be stored in the Velero secret, if `useSecret` is
    # true and `existingSecret` is empty. This should be the contents
    # of your IAM credentials file.
    secretContents:
      AZURE_SUBSCRIPTION_ID: #############################
      AZURE_TENANT_ID: #############################
      AZURE_CLIENT_ID: #############################
      AZURE_CLIENT_SECRET: #############################
      AZURE_RESOURCE_GROUP: #############################
      AZURE_CLOUD_NAME: AzurePublicCloud
    # additional key/value pairs to be used as environment variables such as "DIGITALOCEAN_TOKEN: <your-key>". Values will be stored in the secret.
    extraEnvVars: {}

  # Whether to create backupstoragelocation crd, if false => do not create a default backup location
  backupsEnabled: true
  # Whether to create volumesnapshotlocation crd, if false => disable snapshot feature
  snapshotsEnabled: true

  # Whether to deploy the restic daemonset.
  deployRestic: false

  restic:
    podVolumePath: /var/lib/kubelet/pods
    privileged: false
    # Pod priority class name to use for the Restic daemonset. Optional.
    priorityClassName: {}
    # Resource requests/limits to specify for the Restic daemonset deployment. Optional.
    resources: {}
    # Tolerations to use for the Restic daemonset. Optional.
    tolerations: []

    # Extra volumes for the Restic daemonset. Optional.
    extraVolumes: []

    # Extra volumeMounts for the Restic daemonset. Optional.
    extraVolumeMounts: []

    # SecurityContext to use for the Velero deployment. Optional.
    # Set fsGroup for `AWS IAM Roles for Service Accounts`
    # see more informations at: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
    securityContext: {}
      # fsGroup: 1337

  # Backup schedules to create.
  # Eg:
  # schedules:
  #   mybackup:
  #      labels:
  #        myenv: foo
  #     schedule: "0 0 * * *"
  #     template:
  #       ttl: "240h"
  #       includedNamespaces:
  #        - foo
  schedules: {}

  # Velero ConfigMaps.
  # Eg:
  # configMaps:
  #   restic-restore-action-config:
  #     labels:
  #       velero.io/plugin-config: ""
  #       velero.io/restic: RestoreItemAction
  #     data:
  #       image: velero/velero-restic-restore-helper:v1.3.1
  configMaps: {}

  ##
  ## End of additional Velero resource settings.
  ##
```

chart.yaml

```

apiVersion: v2
name: velero
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

dependencies:
- name: velero
  version: "2.12.13"
  repository: "https://vmware-tanzu.github.io/helm-charts/"

```

**Comment by michaelhaycroft** [comment]
I believe the reason this is happening is because the Helm chart is not setting the below environment variables on the pod spec. I could be wrong.
If you do a dry run of `velero install --dry-run -o yaml --provider "azure" --plugins "velero/velero-plugin-for-microsoft-azure" ... (etcetera) ` you will see these environment variables are specified.
```
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
```
The resultant deployment in my cluster does not have these environment variables set. I manually added them using `kubectl apply` to test this theory and the pod started working after that.

**Comment by carlisia** [comment]
> secretContents:
  cloud: |
    AZURE_SUBSCRIPTION_ID: #############################
    AZURE_TENANT_ID: #############################
    AZURE_CLIENT_ID: #############################
    AZURE_CLIENT_SECRET: #############################
    AZURE_RESOURCE_GROUP: #############################
    AZURE_CLOUD_NAME: AzurePublicCloud

Let's add the above snippet to the `values.yaml` file so people know how to format this properly.
